# Generated by Django 4.0.3 on 2022-10-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='название проживания'),
        ),
    ]
